#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8081/
#          predicates:
#           - Path=/consultationetrendezvous/**
#

#        - id: r3
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/medecinsEtpatients/**

#
#  application:
#    name: gateway-service
#
#
#server:
#  port: 9999
#
